スタイルの調整など
kounoike/web-ts-player pull request #9
Opened 2022-01-23 07:40 UTC by tsukumijima

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/39271166/150669053-30e50fae-f364-42c7-8925-29af9f23a921.png">

プレイヤー画面のスタイルの調整を行い、広いディスプレイでなくても映像や統計グラフが画面内に収まるようにしました。
また、ドロワーメニューのスタイルを改善し、より見やすくしました。

React はほとんど書いた事がないので、お作法に則っていない部分があればどしどし書き直していただいて構いません。
よろしくお願いします。

2022-01-23 07:51 UTC, kounoike requested changes
ちょっと後で動かして確認しますが、まずは単純にコード上でわかることを修正お願いします

2022-01-23 07:51 UTC, kounoike commented on pages/index.tsx
> +            <InputLabel id="demo-simple-select-label">Services</InputLabel>
idをちゃんと考えてつけてもらえますか？

2022-01-23 07:51 UTC, kounoike commented on pages/index.tsx
> +              labelId="demo-simple-select-label"
当たり前ですけど、ここも上に合わせて。

2022-01-23 07:51 UTC, kounoike commented
ちなみに、PRはmainでコミットしていくんじゃなくて、ブランチ作っておいた方が何かと便利ですよ

2022-01-23 08:25 UTC, tsukumijima commented on pages/index.tsx
> +            <InputLabel id="demo-simple-select-label">Services</InputLabel>
大変失礼しました… 修正しました。

2022-01-24 14:24 UTC, kounoike approved these changes
LGTM!

2022-01-24 14:24 UTC, merged